apiVersion: v1
kind: Pod
metadata: 
  name: my-simple-app-pod
  labels: 
    app: my-simple-app-pod
spec:
  containers:
  - name: my-simple-app
    image: jtiagosantos/my-simple-app:v1
    ports:
      - containerPort: 8080